remove failure component

diff --git a/.github/workflows/JooEun-Jeong-action.yml b/.github/workflows/JooEun-Jeong-action.yml
--- a/.github/workflows/JooEun-Jeong-action.yml
+++ b/.github/workflows/JooEun-Jeong-action.yml
@@ -40,14 +40,14 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       
-      - name: fail component_get pr body
-        id: failed
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          exit 1
-          echo "pull_request_body=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
-          echo "PR BODY: ${{ steps.failed.outputs.pull_request_body }}"
+      # - name: fail component_get pr body
+      #   id: failed
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     exit 1
+      #     echo "pull_request_body=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
+      #     echo "PR BODY: ${{ steps.failed.outputs.pull_request_body }}"
 
       - name: Failed send a slack alarm
         if: ${{ failure() }}
