update

diff --git a/.github/workflows/JooEun-Jeong-action.yml b/.github/workflows/JooEun-Jeong-action.yml
--- a/.github/workflows/JooEun-Jeong-action.yml
+++ b/.github/workflows/JooEun-Jeong-action.yml
@@ -63,8 +63,9 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "pull_request_body=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
-          echo "PR BODY: ${{ steps.failed.outputs.pull_request_body }}"
+          # echo "pull_request_body=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
+          # echo "PR BODY: ${{ steps.failed.outputs.pull_request_body }}"
+          exit 1
 
       - name: SUCCESS _ send a slack alarm
         shell: bash
